<!DOCTYPE html>

<head>
   <script src="http://code.jquery.com/jquery-1.8.3.js"></script> <!-- jQuery -->
   <meta charset="utf-8">
   <title>Page for test</title>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta name="description" content="qwerty description">
   <link href="<?=$this->sitePath?>bootstarp/css/bootstrap.css" rel="stylesheet">
   <link href="<?=$this->sitePath?>bootstarp/css/bootstrap-responsive.css" rel="stylesheet">
   <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
   <meta name="author" content="">
</head>



<form action="/register" method="post">
<input type="text" class="accordion" name="test" />
<input type="submit" />
</form>

















    <?php
    // Parser JSON
    if(false){
    $str = file_get_contents($this->sitePath.'/files/items_brands.json');
    $obj = json_decode($str);
    var_dump($obj);
    }
    ?>
    <?php if(false){
    /*
     *  INPUT AJAX SAMPLE HTML attr list
     */    
    ?>
<script>
    function keys(val){
        $("datalist").children().remove();
        $("datalist").append('<option>'+(val)+' вы это искали?</option>');
    }
</script>

  <form> 
      <p><input list="cocktail" onkeyup="keys(this.value);"></p>
   <datalist id="cocktail"></datalist> 
  </form> 
    <?php 
    /*
     *  INPUT AJAX SAMPLE HTML attr list
     */ 
    } ?>
